# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-25 21:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero_ID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_id', models.CharField(max_length=200)),
                ('hero_name', models.CharField(max_length=200)),
            ],
        ),
    ]
